# Generated by Django 5.0.1 on 2024-02-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='created_at',
        ),
    ]
