# Generated by Django 5.0.1 on 2024-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
