# Generated by Django 5.0.1 on 2024-02-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_important',
        ),
    ]
